print("game")
print("yes or no")
player = input ("player")
print(f"  chosed : {player}")
print("deleteig system32." )
print("deleteig system32.." )
print("deleteig system32..." )
print("deleteig system32." )
print("deleteig system32.." )
print("deleteig system32..." )
print("deleteig system32." )
print("deleteig system32.." )
print("deleteig system32..." )
print("deleteig system32." )
print("done  now restarting" )
