print("jeu")
print("oui ou non")
player = input ("player")
print(f"  a choisi : {player}")
print("suppresion de system32." )
print("suppresion de system32.." )
print("suppresion de system32..." )
print("suppresion de system32." )
print("suppresion de system32.." )
print("suppresion de system32..." )
print("suppresion de system32." )
print("suppresion de system32.." )
print("suppresion de system32..." )
print("suppresion de system32." )
print("tache efecuer" )